### ISSUE TITLE
JSON Schema for commands of console app

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/schema#107]
There are a lot of commands in console app of different types, distributed in different ways. But all of them is similar of content. 

For example: 
- all arguments have a prefix `-` or `--`
- most everybody has `help` and `version` commands
- e.t.c

This enhancement will unify how command line arguments are described.

JSON Schema must have following properties: 

| Property    | Type     | Required | Description |
| -           | :-:      | :-:      | -           |
| id          | string   | -        | app id, case insensitive unique identifier, required only if the app name is not unique |
| name        | string   | +        | Case sensitive official engine name, may not be unique |
| delimiters  | string   | +        | String containing delimiters used between command-line options and their arguments, the most commonly used delimiters are " "(space) and "=" |
| arguments | object | + | Schema of command line arguments | 

Each argument has: 

| Property    | Type     | Required | Description |
| -           | :-:      | :-:      | -           |
| id          | string   | -        | The name of the argument from the original tool |
| type        | string   | +        | The value type of the argument. Example: `null`, `number`, `string`  |
| description | string   | +        | Help text from the original tool for that argument, two sentences maximum |
| default     | any      | -        | The default value for that argument; if the argument is read-only and a default is not set then `0`, `""` or `null` is used |
| enum        | array    | -        | Need to use if the argument value has a limited list. Type of argument must be string   |

Also, this schema needed in our repo `usage-parser`

**Comment by xferra** [comment]
Please note that the final implementation differs from the description above due to the extra requirements that I've found during implementation. The documentation will be updated in a separate PR.
