### ISSUE TITLE
Create new type of issue 

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/schema#112]
Please, create new type of issue `technical debt` and new issue with it. 

Related #110

**Comment by romanrostislavovich** [comment]
Also, I suggest add a new type `refactoring`. @xferra What do you think about it?

**Comment by xferra** [comment]
`Maintainance` is not good enough?

**Comment by romanrostislavovich** [comment]
It's suitable

**Comment by xferra** [comment]
Then let's reuse it? It's hard to manage a lot of labels
