### ISSUE TITLE
Build test is failed with error JSON Schema draft-06 not found

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/schema#166]
Build test is failed with error JSON Schema draft-06 not found

![image](https://user-images.githubusercontent.com/10900467/43398189-fb745afc-940f-11e8-95af-76dd70e9a742.png)

**Comment by xferra** [comment]
I remember that Travis build passed for previous PR, any idea why?

**Comment by romanrostislavovich** [comment]
Because `json-schema` package for validate all schemas in tests cached JSON Schema draft-06 before (in step `test:source`), but if I run local `test:deploy` we have this error :(
