### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/schema#31]
Please, add automatic publish to the npm with the semantic release. 

`npm release` include only release version of schemas. 

also, add automatic update gh-pages with npm package. 

Recommendation: 
- [semantic release npm](https://github.com/semantic-release/npm)

**Comment by xferra** [comment]
I think this one is done and we can create a separate issue for `gh-pages` deployment?

**Comment by romanrostislavovich** [comment]
Yes.
Issue for deploy to `gh-pages` is #67
