### ISSUE TITLE
Add new type labels

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/schema#65]
Please, add new type labels: 
- `type: ci`
- `type: test`
- `type: documentation`

**Comment by xferra** [comment]
I also have a suggestion to group labels by tye with transparency from 0 to 100 indicating the importance.

Like: High (Red, 0) Medium (Red, 50) Low (Red, 75)

What do you think?

**Comment by romanrostislavovich** [comment]
That sounds good. Only for `priority` labels ?

**Comment by xferra** [comment]
It’s not an issue but please update existing issues 🧐
