### ISSUE TITLE
Add proper $id to templates

### ISSUE THREAD

**Issue by romanrostislavovich** [linterhub/schema#97]
Auto removed property `id` in `language.linguist.json` and `license.spdx.json` schemas if use `gulp import`.

Please, add it's to `template` schemas in folder `src/template`.

**Comment by xferra** [comment]
The issue is still unclear for me.

**Comment by romanrostislavovich** [comment]
`gulp import` getting templates from `src/template` and automatic fill they. Result put in folder `src / collection`. Templates don't include the property  `id`, so schemas `language.linguist.json` and `license.spdx.json`, in folder` src/collection`, also without `id` property after the update.

But this property need for a correct job next command: `test: source`
